# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FEF0E3
background         #151719
cursor             #A98E8E

active_tab_foreground     #151719
active_tab_background     #FEF0E3
inactive_tab_foreground   #FEF0E3
inactive_tab_background   #151719

active_border_color   #FEF0E3
inactive_border_color #151719
bell_border_color     #081219

color0      #3C3E40
color1		#081219
color2		#3F212A
color3		#943132
color4		#2B6571
color5		#916873
color6		#BCA084
color7		#F5E2CF
color8		#AB9E91
color9		#0A1822
color10		#542C38
color11		#C64143
color12		#398797
color13		#C18B99
color14		#FBD5B0
color15		#F5E2CF
