# Apps par défaut.

$edit=${EDITOR:-nano}
$editor = zeditor
$term = kitty # Terminal
$files = nautilus # File Manager

# Default Search Engine for ROFI Search (SUPER S)
$Search_Engine = "https://www.google.com/search?q={}"
